home/urls.py, pclubWebsite/urls.py
Add urls.py for home and change in urls.py for pclubWebsite
Fixes https://github.com/pclubuiet/website/issues/10
=> home/urls.py: Add urls for home app

README.md
The guide for contributing to the pclubuiet website has been improved.
Steps have been added to make sure newcomers can easily contribute.
=> README.md: Improve contribution guide.

README.md
=> README.md: replace PR with Pull Request

.travis.yml, README.md, home/tests.py
* README.md was updated to include the new rules for collaborators to work on issues since we don't require issues to be assigned.
* Tests were added to check successful rendering of homepage and resources page.
=> Enhancements

.travis.yml
Changed 'collecstatic' in "python manage.py collecstatic"
to 'collectstatic'.
Closes https://github.com/pclubuiet/website/issues/53
=> .travis.yml : Correct misspelt command

home/views.py, templates/base.html, templates/home/home.html, templates/home/resources/resources.html
Change home.html destination address and moved resources folder from templates/ to templates/home and base.html file which will be linked to all other templates.
Closes https://github.com/pclubuiet/website/issues/17
=> resources.html: Change home.html address

staticFiles/home/base.css, templates/base.html
Add footer in base.html with links to social sites.
Closes https://github.com/pclubuiet/website/issues/3
=> base.html: Add footer

templates/base.html, templates/home/home.html
Closes https://github.com/pclubuiet/website/issues/42
=> Add about us

staticFiles/home/base.css, templates/base.html
- Added loading page to main website
- Added jQuery code to base.html for running loader animation
- Added loader animation class to base.css
Fixes #79
=> Add loading page

templates/base.html
Fixes issue #87 
Changes:
Added style block to the head.
Added script block to the end of the body (compliant to Google's Best Practices).
Demo Link: /
=> base.html: Add script and style blocks

templates/base.html
=> make navbar responsive

README.md
Updated README.md with the development workflow to be followed.
=> README.md: Update development workflow

home/urls.py, home/views.py, pclubWebsite/settings.py, staticFiles/404.css, templates/404.html
In this commit, I've added a 404 page ('404.html') to the templates directory. My knowledge of Django is limited and therefore, I haven't touched the Python code for the 404 error handling. I've merely created the front-end for the 404 page. 
Related issue: #73
=> Added a 404 page

README.md
=> README.md: Add Codacy badge

README.md
Fixes issue #135
Changes: README.md
=> Truncate white characters at EOL.

Procfile
Add command which will execute migrations automatically.
Closes https://github.com/pclubuiet/website/issues/138
=> Procfile: Add migrate command

templates/base.html
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
Demo Link: [Add here the link where your changes can be seen]
Screenshots for the change:
=> Fix footer at the end of the page

README.md
Added steps for setting up database and user in the PostgreSQL.
Closes https://github.com/pclubuiet/website/issues/145
=> README.md:Add setting up database steps

staticFiles/home/base.css, templates/base.html, templates/sw.js
Used Material CSS to create material navbar that looks and feels like the navbar in native apps on mobile and is of course responsive.
preview: https://gspclub.herokuapp.com
=> Improve navbar - now material

README.md
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
Demo Link: [Add here the link where your changes can be seen]
Screenshots for the change:
=> Add Deploy to heroku badge

README.md
Fix issues #150 
Changes: The command for starting the postgresql service is add, some typos are corrected.
=> Solved Issues in README.md
